[package]
name = "bulletml"
version = "0.1.0"
authors = ["Arnaud de Bossoreille <arnaud.debossoreille@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
indextree = "3.0"
meval = "0.2"
roxmltree = "0.3"

[dev-dependencies]
matches = "0.1"